language: rust
addons:
    apt:
        sources: [ 'ubuntu-toolchain-r-test' ]
        packages: [ 'libgbm-dev', 'gcc-5' ]

rust:
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache:
  directories:
    - $HOME/.cargo

before_install:
- wget http://llvm.org/releases/3.9.0/clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
- tar xf clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz

script:
- cargo build
- cargo test --all
- env LIBCLANG_PATH=`pwd`/clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-14.04/lib CLANG_PATH=`pwd`/clang+llvm-3.9.0-x86_64-linux-gnu-ubuntu-14.04/bin/clang cargo build --features gen
- diff -q gbm-sys/src/gen.rs $(find target -name gen.rs)
