[package]
name = "gbm"
description = "libgbm bindings for rust"
license = "MIT"
documentation = "https://docs.rs/gbm"
repository = "https://github.com/Drakulix/gbm.rs"
version = "0.2.0"
keywords = ["wayland", "gbm", "drm", "bindings"]
categories = ["external-ffi-bindings"]
authors = ["Drakulix (Victor Brekenfeld)"]
exclude = [".travis.yml", ".rustfmt.toml"]

[dependencies]
gbm-sys = { version = "0.1", path = "./gbm-sys" }
libc = "0.2"
wayland-server = { version = "~0.9.9", optional = true }
egli = { version = "~0.2.1", optional = true }
drm = { version = "~0.2.1", optional = true }

[features]
default = ["import-wayland", "import-egl", "drm-support"]
import-wayland = ["wayland-server"]
import-egl = ["egli", "egli/egl_1_5"]
drm-support = ["drm"]
gen = ["gbm-sys/gen"]
